[build]
  publish = "."
  command = ""

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

# Netlify Forms (opcional)
# [[headers]]
#   for = "/forms/*"
#   [headers.values]
#     Content-Type = "application/x-www-form-urlencoded"